"""Léxico de entidades para análise de sentimento baseado em aspectos.

Cada chave é o nome canônico da entidade e o valor é uma lista de variações
(palavras ou expressões que referenciam a mesma entidade).
"""

ASPECTS_LEXICON: dict[str, list[str]] = {
    # ── Pessoas / Personalidades ───────────────────────────────
    "bruno": ["bruno", "torturra", "brunão"],
    "breno": ["breno", "brenão"],
    "lula": ["lula", "luiz inácio", "lulinha", "pintinha"],
    "bolsonaro": ["bolsonaro", "bolso", "mito", "biroliro", "jair"],
    "elon musk": ["elon", "musk", "elão"],
    "neymar": ["neymar", "menino ney", "ney"],
    "cortez": ["cortez", "virusbr"],
    "richard": ["richard", "richards"],
    "cellbits": ["cellbits", "cell", "bits"],
    "alanzoka": ["alan", "alanzoka"],
    "gaules": ["gaules", "gaulês"],
    "casimiro": ["casimiro", "cazé", "caze"],
    "podpah": ["podpah", "podpa"],
    "igor": ["igor", "igor3k", "3k"],
    "goularte": ["goularte", "goulart"],
    "dav jones": ["dav jones", "dav", "davjones"],

    # ── Marcas / Empresas ──────────────────────────────────────
    "youtube": ["youtube", "yt", "youtuba"],
    "twitch": ["twitch", "twitch.tv", "tchutchuca"],
    "twitter": ["twitter", "x", "twit"],
    "instagram": ["instagram", "insta", "ig"],
    "whatsapp": ["whatsapp", "zap", "whats", "wpp"],
    "telegram": ["telegram", "tele", "tlg"],
    "tiktok": ["tiktok", "tik tok", "tt"],
    "discord": ["discord", "dc"],
    "netflix": ["netflix", "netfli", "net"],
    "youtube premium": ["youtube premium", "yt premium", "youtube music"],
    "amazon": ["amazon", "amz", "amazon prime"],
    "google": ["google", "g00gle", "goog"],
    "microsoft": ["microsoft", "ms", "msft"],
    "apple": ["apple", "maçã", "appl"],
    "samsung": ["samsung", "sam"],
    "xiaomi": ["xiaomi"],
    "motorola": ["motorola", "moto"],
    "nvidia": ["nvidia", "nv", "nvidi"],
    "amd": ["amd", "ati"],
    "intel": ["intel", "intelzera"],
    "rockstar": ["rockstar", "rockstar games", "r*"],
    "ubisoft": ["ubisoft", "ubi"],
    "riot": ["riot", "riot games", "rgin"],
    "blizzard": ["blizzard", "blizz", "ativision"],
    "steam": ["steam", "valve", "steam verde"],
    "epic": ["epic", "epic games", "epic store"],

    # ── Produtos / Tecnologias ─────────────────────────────────
    "iphone": ["iphone", "apple iphone"],
    "android": ["android", "droid", "robot"],
    "windows": ["windows", "win", "winda", "windows 10", "windows 11"],
    "linux": ["linux", "linx", "gnu/linux", "ubuntu", "debian", "fedora"],
    "mac": ["mac", "macbook", "macos", "mac os", "maquinha"],
    "playstation": ["playstation", "ps4", "ps5", "plays", "sony"],
    "xbox": ["xbox", "xbox series", "xbox one", "micosoft"],
    "nintendo": ["nintendo", "switch", "nintendinho"],
    "pc": ["pc", "computador", "gabinete", "desktop"],
    "notebook": ["notebook", "laptop"],
    "rtx": ["rtx", "rtx 30", "rtx 40", "placa de vídeo", "placa de video"],
    "ryzen": ["ryzen", "amd ryzen"],
    "core i": ["core i", "i5", "i7", "i9", "intel core"],
    "ssd": ["ssd", "nvme", "m.2"],
    "ram": ["ram", "memória ram", "memoria ram", "ddr4", "ddr5"],
    "fone": ["fone", "headset", "fone de ouvido"],
    "teclado": ["teclado", "keyboard", "mecânico", "mecanico"],
    "mouse": ["mouse", "rato", "gamer mouse"],
    "monitor": ["monitor", "tela", "display"],
    "cadeira": ["cadeira", "cadeira gamer", "mesa"],
}
