"""Léxico de enquadramentos (framing) para análise do discurso em chat de lives.

Cada entrada mapeia uma palavra ou expressão para uma ou mais categorias discursivas.
As 6 categorias são: ataque, defesa, ironia, elogio, pergunta, neutro.
"""

FRAMING_LEXICON: dict[str, list[str]] = {
    # ── ATAQUE ─────────────────────────────────────────────────
    "idiota": ["ataque"],
    "imbecil": ["ataque"],
    "burro": ["ataque"],
    "burra": ["ataque"],
    "lixo": ["ataque"],
    "vergonha": ["ataque"],
    "ridículo": ["ataque"],
    "ridiculo": ["ataque"],
    "patético": ["ataque"],
    "patetico": ["ataque"],
    "cala boca": ["ataque"],
    "seu merda": ["ataque"],
    "você não sabe": ["ataque"],
    "voce nao sabe": ["ataque"],
    "fala besteira": ["ataque"],
    "não tem lógica": ["ataque"],
    "nao tem logica": ["ataque"],
    "que piada": ["ataque", "ironia"],
    "péssimo": ["ataque"],
    "pessimo": ["ataque"],
    "horrível": ["ataque"],
    "horrivel": ["ataque"],
    "desgraça": ["ataque"],
    "desgraca": ["ataque"],
    "maldito": ["ataque"],
    "maldita": ["ataque"],
    "otário": ["ataque"],
    "otario": ["ataque"],
    "babaca": ["ataque"],
    "escroto": ["ataque"],
    "escrota": ["ataque"],
    "arrombado": ["ataque"],
    "arrombada": ["ataque"],
    "vagabundo": ["ataque"],
    "vagabunda": ["ataque"],
    "nojento": ["ataque"],
    "nojenta": ["ataque"],
    "canalha": ["ataque"],
    "hipócrita": ["ataque"],
    "hipocrita": ["ataque"],
    "chato": ["ataque"],
    "chata": ["ataque"],
    "enche o saco": ["ataque"],
    "encheu o saco": ["ataque"],
    "chega de": ["ataque"],
    "para com isso": ["ataque"],
    "para de falar": ["ataque"],
    "vaza": ["ataque"],
    "cai fora": ["ataque"],
    "some": ["ataque"],
    "tnc": ["ataque"],
    "pqp": ["ataque"],
    "vai tomar no cu": ["ataque"],
    "vai se fuder": ["ataque"],
    "vsf": ["ataque"],
    "fdp": ["ataque"],
    "cuzao": ["ataque"],
    "cuzão": ["ataque"],
    "merda": ["ataque"],

    # ── DEFESA ─────────────────────────────────────────────────
    "concordo": ["defesa"],
    "concordamos": ["defesa"],
    "exatamente": ["defesa"],
    "tem razão": ["defesa"],
    "tem razao": ["defesa"],
    "falou tudo": ["defesa"],
    "perfeito": ["defesa"],
    "perfeita": ["defesa"],
    "correto": ["defesa"],
    "correta": ["defesa"],
    "é isso aí": ["defesa"],
    "e isso ai": ["defesa"],
    "você está certo": ["defesa"],
    "voce esta certo": ["defesa"],
    "você tem razão": ["defesa"],
    "voce tem razao": ["defesa"],
    "justamente": ["defesa"],
    "pois é": ["defesa"],
    "pois e": ["defesa"],
    "verdade": ["defesa"],
    "sim senhor": ["defesa"],
    "apoio": ["defesa"],
    "também acho": ["defesa"],
    "tambem acho": ["defesa"],
    "penso igual": ["defesa"],
    "boa colocação": ["defesa"],
    "boa colocacao": ["defesa"],
    "bem colocado": ["defesa"],
    "bem colocada": ["defesa"],
    "com certeza": ["defesa"],
    "certamente": ["defesa"],
    "óbvio": ["defesa"],
    "obvio": ["defesa"],
    "lógico": ["defesa"],
    "logico": ["defesa"],
    "claro": ["defesa"],
    "muito bom": ["defesa"],
    "boa": ["defesa"],

    # ── IRONIA ─────────────────────────────────────────────────
    "kkkk": ["ironia"],
    "kkkkk": ["ironia"],
    "rsrs": ["ironia"],
    "rsrsrs": ["ironia"],
    "🤣": ["ironia"],
    "😏": ["ironia"],
    "🙄": ["ironia"],
    "sério mesmo": ["ironia"],
    "serio mesmo": ["ironia"],
    "sério mesmo?": ["ironia"],
    "serio mesmo?": ["ironia"],
    "que novidade": ["ironia"],
    "claro confia": ["ironia"],
    "aham tá": ["ironia"],
    "aham ta": ["ironia"],
    "nossa que legal": ["ironia"],
    "que bom pra você": ["ironia"],
    "que bom pra voce": ["ironia"],
    "aham": ["ironia"],
    "confia": ["ironia"],
    "claro que sim": ["ironia"],
    "imagina": ["ironia"],
    "só que não": ["ironia"],
    "so que nao": ["ironia"],
    "boa sorte": ["ironia"],
    "hmm": ["ironia"],
    "hmmm": ["ironia"],
    "duvido": ["ironia"],
    "uhum": ["ironia"],
    "seilá": ["ironia"],
    "sei la": ["ironia"],

    # ── ELOGIO ─────────────────────────────────────────────────
    "parabéns": ["elogio"],
    "parabens": ["elogio"],
    "ótimo": ["elogio"],
    "otimo": ["elogio"],
    "excelente": ["elogio"],
    "incrível": ["elogio"],
    "incrivel": ["elogio"],
    "fantástico": ["elogio"],
    "fantastico": ["elogio"],
    "fantástica": ["elogio"],
    "fantastica": ["elogio"],
    "genial": ["elogio"],
    "maravilhoso": ["elogio"],
    "maravilhosa": ["elogio"],
    "obrigado": ["elogio"],
    "obrigada": ["elogio"],
    "adorei": ["elogio"],
    "sensacional": ["elogio"],
    "brabo": ["elogio"],
    "brabíssimo": ["elogio"],
    "brabissimo": ["elogio"],
    "gênio": ["elogio"],
    "genio": ["elogio"],
    "fera": ["elogio"],
    "monstro": ["elogio"],
    "lendário": ["elogio"],
    "lendario": ["elogio"],
    "linda": ["elogio"],
    "lindo": ["elogio"],
    "bonito": ["elogio"],
    "bonita": ["elogio"],
    "show": ["elogio"],
    "top": ["elogio"],
    "demais": ["elogio"],
    "muito bom": ["elogio"],
    "muito boa": ["elogio"],
    "melhor": ["elogio"],
    "carisma": ["elogio"],
    "carismático": ["elogio"],
    "carismatico": ["elogio"],
    "inteligente": ["elogio"],
    "sábio": ["elogio"],
    "sabio": ["elogio"],
    "respeito": ["elogio"],
    "admiro": ["elogio"],
    "inspiração": ["elogio"],
    "inspirador": ["elogio"],
    "obrigadão": ["elogio"],
    "obrigadao": ["elogio"],
    "valeu": ["elogio"],
    "vlw": ["elogio"],
    "brigado": ["elogio"],
    "brigada": ["elogio"],
    "amei": ["elogio"],
    "amando": ["elogio"],
    "aula": ["elogio"],

    # ── PERGUNTA ───────────────────────────────────────────────
    "quem?": ["pergunta"],
    "quem": ["pergunta"],
    "quando?": ["pergunta"],
    "quando": ["pergunta"],
    "onde?": ["pergunta"],
    "onde": ["pergunta"],
    "por quê?": ["pergunta"],
    "por que?": ["pergunta"],
    "porque?": ["pergunta"],
    "por quê": ["pergunta"],
    "por que": ["pergunta"],
    "como assim?": ["pergunta"],
    "como assim": ["pergunta"],
    "alguém sabe": ["pergunta"],
    "alguem sabe": ["pergunta"],
    "me explica": ["pergunta"],
    "explica": ["pergunta"],
    "o que é": ["pergunta"],
    "o que foi": ["pergunta"],
    "o que está": ["pergunta"],
    "o que ta": ["pergunta"],
    "o que você": ["pergunta"],
    "o que voce": ["pergunta"],
    "qual é": ["pergunta"],
    "qual e": ["pergunta"],
    "quanto": ["pergunta"],
    "quanta": ["pergunta"],
    "quantos": ["pergunta"],
    "quantas": ["pergunta"],
    "como funciona": ["pergunta"],
    "como faz": ["pergunta"],
    "como fazer": ["pergunta"],
    "pode explicar": ["pergunta"],
    "pode repetir": ["pergunta"],
    "pode falar": ["pergunta"],
    "você acha": ["pergunta"],
    "voce acha": ["pergunta"],
    "o que acha": ["pergunta"],
    "o que voce acha": ["pergunta"],
    "tem como": ["pergunta"],
    "será que": ["pergunta"],
    "sera que": ["pergunta"],
    "vai ter": ["pergunta"],
    "vai dar": ["pergunta"],
    "vai rolar": ["pergunta"],
    "que horas": ["pergunta"],
    "quanto tempo": ["pergunta"],
    "qual o nome": ["pergunta"],
    "qual o link": ["pergunta"],
    "alguém tem": ["pergunta"],
    "alguem tem": ["pergunta"],
    "alguém viu": ["pergunta"],
    "alguem viu": ["pergunta"],
    "consegue": ["pergunta"],
}
