MODALITY_LEXICON: dict[str, list[str]] = {
    "certeza": [
        "certamente",
        "com certeza",
        "sem dúvida",
        "sem dúvidas",
        "claro que",
        "óbvio",
        "evidente",
        "é fato",
        "é certo",
        "lógico",
        "claramente",
        "indiscutivelmente",
        "com toda certeza",
        "não há dúvida",
        "com absoluta certeza",
        "garantido",
        "garanto que",
        "afirmo que",
        "óbvio que",
    ],
    "duvida": [
        "talvez",
        "quem sabe",
        "será que",
        "será?",
        "não sei",
        "acho que",
        "acho q",
        "pode ser",
        "não tenho certeza",
        "duvido",
        "difícil saber",
        "provavelmente",
        "possivelmente",
        "me pergunto",
        "fiquei na dúvida",
        "incerto",
        "não tenho ideia",
        "vai saber",
        "sei lá",
        "sei la",
        "não sei não",
        "será mesmo",
    ],
    "enfase": [
        "muito",
        "demais",
        "super",
        "extremamente",
        "realmente",
        "incrível",
        "sensacional",
        "absolutamente",
        "total",
        "totalmente",
        "completamente",
        "impressionante",
        "fantástico",
        "fantástica",
        "maravilhoso",
        "maravilhosa",
        "excelente",
        "perfeito",
        "perfeita",
        "espetacular",
    ],
}
