"""Léxico de expressões de sarcasmo/ironia para detecção em chat de lives.

Cada entrada é uma string que, se encontrada em uma mensagem,
sugere tom sarcástico ou irônico.
"""

SARCASM_LEXICON: list[str] = [
    # Ironia explícita
    "grande coisa",
    "que legal",
    "que legalzinho",
    "que legalzinha",
    "aham, tá",
    "aham ta",
    "aham, confia",
    "claro, confia",
    "claro confia",
    "sério mesmo?",
    "serio mesmo?",
    "sério? aham",
    "serio? aham",
    "nossa, que novidade",
    "nossa que novidade",
    "parabéns, hein",
    "parabens, hein",
    "parabéns hein",
    "parabens hein",
    "você é um gênio",
    "voce e um genio",
    "tá certíssimo",
    "ta certissimo",
    "tá certissimo",
    "que surpresa",
    "que surpresa hein",
    "jura?",
    "jura",
    "mentira?",
    "mentira",
    "pode crer",
    "confia",
    "aham",
    "uhum",
    "sim, claro",
    "sim claro",
    "lógico que sim",
    "logico que sim",
    "só que não",
    "so que nao",
    "imagina",
    "imagina, hein",
    "boa sorte",
    "boa sorte com isso",
    "vai dar certo",
    "confia que dá",
    "confia q da",
    "sei, confia",
    "sei, aham",
    # Riso irônico / deboche
    "kkkk",
    "kkkkk",
    "kkkkkk",
    "rsrs",
    "rsrsrs",
    "hahaha",
    "hahahaha",
    "😂",
    "🤣",
    "🙄",
    "😏",
    "😒",
    # Expressões de falsa admiração
    "que pessoa incrível",
    "que pessoa incrivel",
    "que exemplo",
    "que exemplo hein",
    "que profissional",
    "que profissional hein",
    "lindo, hein",
    "lindo hein",
    "linda, hein",
    "linda hein",
    "bonito, hein",
    "bonito hein",
    # Deboche direto
    "tá bom, confia",
    "ta bom, confia",
    "tá bom confia",
    "ta bom confia",
    "tá, tá",
    "ta ta",
    "tá certo",
    "ta certo",
    "certo, certo",
    "beleza, confia",
    "blz confia",
    # Falso elogio
    "muito inteligente da sua parte",
    "muito esperto",
    "gênio da internet",
    "genio da internet",
    "sábio",
    "sabio",
    "mestre dos magos",
    "parabéns pra você",
    "parabens pra voce",
    # Questionamento irônico
    "sério?",
    "serio?",
    "é mesmo?",
    "e mesmo?",
    "você acha mesmo?",
    "voce acha mesmo?",
    "tá falando sério?",
    "ta falando serio?",
    "falando sério?",
    "falando serio?",
    "não me diga",
    "nao me diga",
]
