PORTUGUESE_STOPWORDS = {
    "a", "o", "os", "as", "um", "uma", "uns", "umas",
    "de", "do", "da", "dos", "das", "no", "na", "nos", "nas",
    "ao", "aos", "à", "às", "com", "por", "para", "sem", "sob", "sobre",
    "e", "é", "em", "que", "se", "como", "mas", "ou", "quando", "porque",
    "muito", "pouco", "mais", "menos", "muitos", "muitas", "poucos", "poucas",
    "foi", "era", "ser", "sou", "somos", "são", "estou", "está", "estamos", "estão",
    "estive", "esteve", "estivemos", "estiveram", "estava", "estavam", "estivéssemos",
    "tive", "teve", "tivemos", "tiveram", "terei", "terá", "teremos", "terão",
    "tenho", "tem", "temos", "têm", "tinha", "tinham", "tivesse", "tivessem",
    "haver", "há", "havia", "haviam", "houve", "houveram", "houverá", "houveram",
    "vou", "vai", "vamos", "vão", "iria", "iríamos", "iriam",
    "me", "te", "se", "nos", "vos", "lhe", "lhes",
    "eu", "tu", "ele", "ela", "nós", "vós", "eles", "elas",
    "meu", "minha", "meus", "minhas",
    "teu", "tua", "teus", "tuas",
    "seu", "sua", "seus", "suas",
    "nosso", "nossa", "nossos", "nossas",
    "vosso", "vossa", "vossos", "vossas",
    "deste", "desta", "destes", "destas",
    "desse", "dessa", "desses", "dessas",
    "daquele", "daquela", "daqueles", "daquelas",
    "este", "esta", "estes", "estas",
    "esse", "essa", "esses", "essas",
    "aquele", "aquela", "aqueles", "aquelas",
    "isto", "isso", "aquilo",
    "quem", "qual", "quais", "onde", "como", "quanto", "quantos",
    "nenhum", "nenhuma", "nenhuns", "nenhumas",
    "algum", "alguma", "alguns", "algumas",
    "cada", "todo", "toda", "todos", "todas",
    "outro", "outra", "outros", "outras",
    "mesmo", "mesma", "mesmos", "mesmas",
    "próprio", "própria", "próprios", "próprias",
    "tal", "tais",
    "kkk", "kk", "k", "rs"
}